In [3]:
import numpy as np

In [4]:
a1 = np.array([1,2,3])

In [5]:
type(a1) , a1

(numpy.ndarray, array([1, 2, 3]))

In [6]:
a2 = np.arange(0,10,2)
a2

array([0, 2, 4, 6, 8])

In [7]:
np.random.seed(10)

a3 = np.random.randint(0,100,(20,10))
a3

array([[ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0],
       [40, 36, 16, 11, 54, 88, 62, 33, 72, 78],
       [49, 51, 54, 77, 69, 13, 25, 13, 92, 86],
       [30, 30, 89, 12, 65, 31, 57, 36, 27, 18],
       [93, 77, 22, 23, 94, 11, 28, 74, 88,  9],
       [15, 18, 80, 71, 88, 11, 17, 46,  7, 75],
       [28, 33, 84, 96, 88, 44,  5,  4, 71, 88],
       [88, 50, 54, 34, 15, 77, 88, 15,  6, 85],
       [22, 11, 12, 92, 96, 62, 57, 79, 42, 57],
       [97, 50, 45, 40, 89, 73, 37,  0, 18, 23],
       [ 3, 29, 16, 84, 82, 14, 51, 79, 17, 50],
       [53, 25, 48, 17, 32, 81, 80, 41, 90, 12],
       [30, 81, 17, 16,  0, 31, 73, 64, 38, 22],
       [96, 66, 67, 62, 95, 99, 27, 82, 62, 77],
       [48, 93, 75, 86, 37, 11, 21, 33, 95, 43],
       [88, 96, 73, 40, 43, 90, 71,  8, 85, 72],
       [28, 30, 89, 25, 78, 81, 85, 62, 13, 41],
       [33,  4, 87, 94, 28, 39, 91,  9,  7, 22],
       [32,  3,  9, 52, 76, 68, 30, 70, 74, 30],
       [ 9,  2, 65, 13, 75, 52,  5, 93, 84, 48]])

In [8]:
zeros = np.zeros((10,10),int)
zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
ones = np.ones((5,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.random.seed(10)
mat = np.random.randint(0,10,(10,10))
mat

array([[9, 4, 0, 1, 9, 0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0, 4, 6, 8, 1, 8],
       [4, 1, 3, 6, 5, 3, 9, 6, 9, 1],
       [9, 4, 2, 6, 7, 8, 8, 9, 2, 0],
       [6, 7, 8, 1, 7, 1, 4, 0, 8, 5],
       [4, 7, 8, 8, 2, 6, 2, 8, 8, 6],
       [6, 5, 6, 0, 0, 6, 9, 1, 8, 9],
       [1, 2, 8, 9, 9, 5, 0, 2, 7, 3],
       [0, 4, 2, 0, 3, 3, 1, 2, 5, 9],
       [0, 1, 0, 1, 9, 0, 9, 2, 1, 1]])

In [13]:
mat[:,0]

array([9, 8, 4, 9, 6, 4, 6, 1, 0, 0])

In [14]:
mat[4:9,3:7] = 0

In [15]:
mat

array([[9, 4, 0, 1, 9, 0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0, 4, 6, 8, 1, 8],
       [4, 1, 3, 6, 5, 3, 9, 6, 9, 1],
       [9, 4, 2, 6, 7, 8, 8, 9, 2, 0],
       [6, 7, 8, 0, 0, 0, 0, 0, 8, 5],
       [4, 7, 8, 0, 0, 0, 0, 8, 8, 6],
       [6, 5, 6, 0, 0, 0, 0, 1, 8, 9],
       [1, 2, 8, 0, 0, 0, 0, 2, 7, 3],
       [0, 4, 2, 0, 0, 0, 0, 2, 5, 9],
       [0, 1, 0, 1, 9, 0, 9, 2, 1, 1]])

In [51]:
mat1 = mat.copy()
mat1

array([[9, 4, 0, 1, 9, 0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0, 4, 6, 8, 1, 8],
       [4, 1, 3, 6, 5, 3, 9, 6, 9, 1],
       [9, 4, 2, 6, 7, 8, 8, 9, 2, 0],
       [6, 7, 8, 0, 0, 0, 0, 0, 8, 5],
       [4, 7, 8, 0, 0, 0, 0, 8, 8, 6],
       [6, 5, 6, 0, 0, 0, 0, 1, 8, 9],
       [1, 2, 8, 0, 0, 0, 0, 2, 7, 3],
       [0, 4, 2, 0, 0, 0, 0, 2, 5, 9],
       [0, 1, 0, 1, 9, 0, 9, 2, 1, 1]])

In [16]:
mat.max()

9

In [17]:
mat.argmax()

0

In [18]:
mat.min()

0

In [19]:
mat.argmin()

2

In [20]:
mat.mean()

3.7